### PR TITLE
Fixed logging include.

### PR DESCRIPTION
**Pull request by skasperski**

### CODE REVIEW

**Comment by chhtz** [comment]
It should actually be `#include <base-logging/Logging.hpp>`, if you are on master.

**Comment by skasperski** [comment]
Ok, done. But I don't understand why the include is called base-logging. The autoproj-package is called "base/logging", so I think the include should be "base/logging/Logging.hpp", like e.g. in "base/types/Transform.hpp".

**Comment by chhtz** [comment]
Thanks for the patch!
I don't really know about the package naming. Maybe @planthaber can elaborate on that.

**Comment by planthaber** [comment]
Now base-logging follows the rock standard, rather than the non-standard base-types package.

e.g. the include path for slam/octomap is `<octomap/header.h>` rather than `<slam/octomap/header.h>`

base-types is the only package, that does it differently (and is hard to change though)

**Comment by skasperski** [comment]
But still there is no package called base-logging, so the include should be "logging/Logging.hpp".

**Comment by planthaber** [comment]
actually that's true but is in line with the other package names base-lib and base-types, the rock_standard_layout() cmake macro does afaik not allow to install the headers in a directory not having the package name. We could change the package name completely though

**Pull request merged**
